= OpenZeppelin Foundry Upgrades API

== Contract name formats

Contract names must be provided in certain scenarios and must be in specific formats. The following are the required formats for each scenario.

=== Foundry artifact format

Use with:

* `contractName` parameter
* `referenceContract` option

When using functions that take a contract name, or the `referenceContract` option, the string must be in one of the following formats (to be compliant with Foundry's https://book.getfoundry.sh/cheatcodes/get-code[getCode] cheatcode):

* the Solidity file name, e.g. `ContractV1.sol`
* the Solidity file name and the contract name, e.g. `ContractV1.sol:ContractV1`
* the artifact path relative to the project root directory, e.g. `out/ContractV1.sol/ContractV1.json`

=== Annotation format

Use with:

* `@custom:oz-upgrades-from <reference>` annotation

When using the `@custom:oz-upgrades-from <reference>` annotation, the reference contract name must be in one of the following formats (to be compliant with the https://docs.openzeppelin.com/upgrades-plugins/api-core#define-reference-contracts[OpenZeppelin Upgrades CLI]):

* the contract name, e.g. `ContractV1`
* fully qualified contract name, e.g. `contracts/tokens/ContractV1.sol:ContractV1`

If the `referenceBuildInfoDir` option is set, include the build info directory name before the contract name, resulting in one of the following formats:

* the reference build info directory name and the contract name, e.g. `build-info-v1:ContractV1`
* the reference build info directory name and the fully qualified contract name, e.g. `build-info-v1:contracts/tokens/ContractV1.sol:ContractV1`

== Common Options

The following options can be used with some of the below functions. See https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/blob/main/src/Options.sol[Options.sol] for detailed descriptions of each option.

include::Options.adoc[]

== Upgrades.sol

include::Upgrades.adoc[]

== LegacyUpgrades.sol

include::LegacyUpgrades.adoc[]

== Defender.sol

include::Defender.adoc[]
